---
version: 2.1

workflows:
  on_build:
    jobs:
      - validate_documents:
          name: build and artifact
          filters: {branches:{ignore:[master]}}

jobs:
  validate_documents:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: install markdownlint
          command: gem install mdl
      - run:
          name: run markdownlint
          command: mdl -r MD001,MD002,MD003,MD004,MD005,MD006,MD007,MD009,MD010,MD011,MD012,MD018,MD019,MD022,MD023,MD025,MD027,MD030,MD031,MD032,MD037,MD038,MD039,MD046 .
