name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

jobs:
  validate_documents:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Run markdownlint
        uses: actionshub/markdownlint@master
  
  terraform_checks:
    runs-on: "ubuntu-latest"
    needs: validate_documents
    strategy:
      max-parallel: 1
      matrix:
        include:
          - tf_workspace: "development"

          - tf_workspace: "preproduction"

          - tf_workspace: "production"
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Setup Workspace
        run: echo TF_WORKSPACE=${{ matrix.tf_workspace }} >> $GITHUB_ENV

      - name: Terraform init
        working-directory: ./infrastructure/terraform
        run: |
          terraform init
      - name: Terraform formatting
        working-directory: ./infrastructure/terraform
        run: |
          terraform fmt -diff -check -recursive  
      - name: Terraform validate
        working-directory: ./infrastructure/terraform
        run: |
          terraform validate
      
      - name: Terraform Plan
        working-directory: ./infrastructure/terraform
        run: |
          terraform plan -input=false
      
