name: Deploy

on:
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

jobs:
  terraform_apply:
    name: Validate ${{ matrix.tf_workspace }}
    runs-on: "ubuntu-latest"
    env:
      TF_VAR_pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}
    strategy:
      matrix:
        include:
          - tf_workspace: "development"

          - tf_workspace: "preproduction"

          - tf_workspace: "production"
    steps:
      - uses: actions/checkout@v2
      - name: "Set terraform version [${{ matrix.tf_workspace }}]"
        id: set-terraform-version
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@ea1e81f43e7593acd74cc114085930f5f54914a2 # v3.1.7
        with:
          terraform_directory: ./infrastructure/terraform

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.set-terraform-version.outputs.version }}

      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-session-name: GitHubActionsTerraform

      - name: Setup Workspace
        run: echo TF_WORKSPACE=${{ matrix.tf_workspace }} >> $GITHUB_ENV

      - name: Terraform init
        working-directory: ./infrastructure/terraform
        run: |
          terraform init

      - name: Plan ${{ matrix.tf_workspace }}
        working-directory: ./infrastructure/terraform
        run: |
          terraform init -input=false
          terraform plan -lock-timeout=300s -input=false -parallelism=30

      - name: Apply ${{ matrix.tf_workspace }}
        working-directory: ./infrastructure/terraform
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30
