name: Deploy

on:
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

jobs:
  terraform_apply:
    runs-on: "ubuntu-latest"
    strategy:
      max-parallel: 1
      matrix:
        include:
          - tf_workspace: "development"

          - tf_workspace: "preproduction"

          - tf_workspace: "production"
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SIRIUS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SIRIUS }}
          aws-region: eu-west-1
          role-session-name: GitHubActionsTerraform
      - name: Setup Workspace
        run: echo TF_WORKSPACE=${{ matrix.tf_workspace }} >> $GITHUB_ENV
      
      - name: Terraform init
        working-directory: ./infrastructure/terraform
        run: |
          terraform init
      - name: Plan ${{ matrix.tf_workspace }}
        run: |
          terraform init -input=false
          terraform plan -lock-timeout=300s -input=false -parallelism=30

      - name: Apply ${{ matrix.tf_workspace }}
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30

