name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Monday, at 17:40 UTC
    - cron: '40 17 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: ministryofjustice/opg-repository-scanner@latest
